-- What the pipeline did, per run and per step.

USE DATABASE AIRLINE_DWH;

-- One line per run.
SELECT RUN_ID,
       PIPELINE_NAME,
       COUNT(*)                          AS steps,
       SUM(IFF(STATUS = 'FAILED', 1, 0)) AS steps_failed,
       SUM(ROWS_INSERTED)                AS rows_inserted,
       SUM(ROWS_UPDATED)                 AS rows_updated,
       MIN(STARTED_AT)                   AS started_at,
       ROUND(SUM(DURATION_SEC), 2)       AS total_sec
FROM META.ETL_AUDIT_LOG
GROUP BY RUN_ID, PIPELINE_NAME
ORDER BY started_at DESC;

-- Step detail for the most recent run.
SELECT TARGET_OBJECT, OPERATION, ROWS_INSERTED, ROWS_UPDATED,
       ROUND(DURATION_SEC, 2) AS duration_sec, STATUS, ERROR_MESSAGE, QUERY_ID
FROM META.ETL_AUDIT_LOG
WHERE RUN_ID = (SELECT RUN_ID FROM META.ETL_AUDIT_LOG ORDER BY AUDIT_ID DESC LIMIT 1)
ORDER BY AUDIT_ID;

-- Row counts across the three layers.
SELECT 'RAW.AIRLINE_RAW'              AS object_name, COUNT(*) AS row_count FROM RAW.AIRLINE_RAW
UNION ALL SELECT 'CORE.DIM_PASSENGER',           COUNT(*) FROM CORE.DIM_PASSENGER
UNION ALL SELECT 'CORE.DIM_AIRPORT',             COUNT(*) FROM CORE.DIM_AIRPORT
UNION ALL SELECT 'CORE.DIM_DATE',                COUNT(*) FROM CORE.DIM_DATE
UNION ALL SELECT 'CORE.FCT_FLIGHT_BOOKING',      COUNT(*) FROM CORE.FCT_FLIGHT_BOOKING
UNION ALL SELECT 'MART.AGG_FLIGHT_STATUS_DAILY', COUNT(*) FROM MART.AGG_FLIGHT_STATUS_DAILY;

-- Whether anything is waiting to be processed.
SELECT 'STRM_AIRLINE_RAW_DIM_PASSENGER' AS stream, SYSTEM$STREAM_HAS_DATA('RAW.STRM_AIRLINE_RAW_DIM_PASSENGER') AS has_data
UNION ALL SELECT 'STRM_AIRLINE_RAW_DIM_AIRPORT',    SYSTEM$STREAM_HAS_DATA('RAW.STRM_AIRLINE_RAW_DIM_AIRPORT')
UNION ALL SELECT 'STRM_AIRLINE_RAW_DIM_DATE',       SYSTEM$STREAM_HAS_DATA('RAW.STRM_AIRLINE_RAW_DIM_DATE')
UNION ALL SELECT 'STRM_AIRLINE_RAW_FCT_BOOKING',    SYSTEM$STREAM_HAS_DATA('RAW.STRM_AIRLINE_RAW_FCT_BOOKING')
UNION ALL SELECT 'STRM_FCT_BOOKING_MART',           SYSTEM$STREAM_HAS_DATA('CORE.STRM_FCT_BOOKING_MART');
